### ISSUE TITLE
Get only marker coordinates 

### ISSUE THREAD

**Issue by redcat22** [pyomeca/tutorials#1]
Is possibel to get only marker coordinates without angles, forces, moments etc? 
Basicaly Iam interested in get each type of data independently for:

Marker coordinates
Angles
Forces
Moments
Powers

**Comment by romainmartinez** [comment]
Marker coordinates are interfaced in the `Markers3d` class.
You can use this class to open and manipulate three-dimensional data (e.g. x, y, z).

```python
from pyomeca import Markers3d

data_path = 'your_data.c3d'
data = Markers3d.from_c3d(data_path)

# your analysis
processed = data.band_pass(freq=data.get_rate, order=4, cutoff=[10, 425])
```

Simirarly, you can use the `Analogs3d` class to manipulate one-dimensional data (e.g. EMG, forces, etc.) 

```python
from pyomeca import Analogs3d

data_path = 'your_data.c3d'
data = Analogs3d.from_c3d(data_path)
```

**Comment by pariterre** [comment]
@romainmartinez 
Actually what he meant is that points include points, angles and power, while analogs include analogs, forces and moments, but they are not separated.

@redcat22 The main reason for that is c3d, by standard, cannot include anything else that points data and analog data. Vicon actually found a workaround for this which consist in merging data.

I've been asked before to provide an easy way to split these data. I am not sure that this is a good idea. The main reason is that it is highly Vicon/Nexus version dependent and not at all compliant to the standard. So far, I've decided not to implement this...

In MATLAB and python, though it can be easily done : 
As soon as you have your data, you can retrieve only the markers by splicing them. For example : 
 ```python
from ezc3d import c3d

# Assuming you know how many markers you have...
number_of_markers = 10

# Open your file
c = c3d("../markers_analogs.c3d")

# Get the points data
data = c['data']['points']

# Slice the data
markers = data[:, :number_of_markers, :]

# Print the markers
print(markers)
```

Or as @romainmartinez pointed out, you can to do the slicing on Markers3d from the pyomeca toolbox as well

**Comment by redcat22** [comment]
In fact is not so easy, because we dont have the number of the markers only (at least I was unable to find that number in the c3d) the number that we get also include angles, moments, etc. 

I manage to use an workaround based on the labels but is not the more elegant solution
I already have done that in the code that I posted here ( https://github.com/pyomeca/ezc3d/issues/51)

**Comment by pariterre** [comment]
Exact..
If I were to  create a function that extract only markers, I probably would have to base it on interpreting the names..

Maybe there is some sort of tag that Nexus leaves in the c3d... I'll have a look soon
